"""PostgreSQL integration coverage for catalog capture and target receipts."""

from __future__ import annotations

import os
from uuid import uuid4

import psycopg
import pytest
from proteus import catalog, executor, schema
from psycopg import conninfo, sql
from psycopg.rows import dict_row

TEST_DSN = os.environ.get(
    'PROTEUS_TEST_DSN',
    os.environ.get(
        'PROTEUS_SANDBOX_URL', 'postgresql://postgres:proteus_local@localhost:55433/postgres'
    ),
)


@pytest.fixture
async def database():
    name = f'proteus_test_{uuid4().hex}'
    try:
        admin = await psycopg.AsyncConnection.connect(
            TEST_DSN, autocommit=True, row_factory=dict_row
        )
    except psycopg.OperationalError:
        pytest.skip('PostgreSQL is unavailable. Set PROTEUS_TEST_DSN to run integration tests.')
    try:
        await admin.execute(sql.SQL('CREATE DATABASE {}').format(sql.Identifier(name)))
        parameters = conninfo.conninfo_to_dict(TEST_DSN)
        parameters['dbname'] = name
        dsn = conninfo.make_conninfo(**parameters)
        yield dsn
    finally:
        await admin.execute(
            sql.SQL('DROP DATABASE IF EXISTS {} WITH (FORCE)').format(sql.Identifier(name))
        )
        await admin.close()


def object_id() -> str:
    return str(uuid4())


@pytest.mark.integration
async def test_catalog_captures_supported_schema_and_reuses_reference_ids(database: str) -> None:
    async with await psycopg.AsyncConnection.connect(database, row_factory=dict_row) as conn:
        await conn.execute(
            """
            CREATE TABLE customers (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                email varchar(40) NOT NULL UNIQUE,
                created_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
                credit numeric(8,2) NOT NULL CHECK (credit >= 0)
            )
            """
        )
        await conn.execute('CREATE INDEX customers_created_idx ON customers (created_at, email)')
        await conn.commit()
        first = await catalog.introspect(conn, 'public')
        assert first['unsupported'] == []
        assert [index['name'] for index in first['snapshot']['tables'][0]['indexes']] == [
            'customers_created_idx'
        ]
        second = await catalog.introspect(conn, 'public', reference=first['snapshot'])
        assert second['unsupported'] == []
        assert second['snapshot'] == first['snapshot']
        assert schema.fingerprint(second['snapshot']) == schema.fingerprint(first['snapshot'])


@pytest.mark.integration
async def test_catalog_reports_unmodeled_pg17_semantics_without_raising(database: str) -> None:
    async with await psycopg.AsyncConnection.connect(database, row_factory=dict_row) as conn:
        await conn.execute('CREATE SCHEMA foreign_schema')
        await conn.execute('CREATE TABLE foreign_schema.parents (id integer PRIMARY KEY)')
        await conn.execute(
            """
            CREATE TABLE catalog_limits (
                value text COLLATE "C",
                plain_value text,
                generated_size integer GENERATED ALWAYS AS (char_length(value)) STORED,
                identity_value integer GENERATED BY DEFAULT AS IDENTITY (START WITH 7),
                CONSTRAINT catalog_limits_unique UNIQUE NULLS NOT DISTINCT (plain_value)
            )
            """
        )
        await conn.execute(
            'CREATE UNIQUE INDEX standalone_nulls_idx ON catalog_limits (plain_value) NULLS NOT DISTINCT'
        )
        await conn.execute(
            'CREATE INDEX descending_idx ON catalog_limits (plain_value DESC NULLS FIRST)'
        )
        await conn.execute(
            'CREATE INDEX opclass_idx ON catalog_limits (plain_value text_pattern_ops)'
        )
        await conn.execute('CREATE INDEX collation_idx ON catalog_limits (plain_value COLLATE "C")')
        await conn.execute("CREATE TABLE invalid_check (value text CHECK (value LIKE 'x%'))")
        await conn.execute(
            'CREATE TABLE cross_schema_reference (parent_id integer REFERENCES foreign_schema.parents (id))'
        )
        await conn.execute(
            """CREATE FUNCTION catalog_trigger() RETURNS trigger LANGUAGE plpgsql AS $$
               BEGIN RETURN NEW; END;
               $$"""
        )
        await conn.execute(
            'CREATE TRIGGER catalog_trigger BEFORE INSERT ON catalog_limits '
            'FOR EACH ROW EXECUTE FUNCTION catalog_trigger()'
        )
        await conn.commit()
        result = await catalog.introspect(conn, 'public')
    reasons = {item['name']: item['reason'] for item in result['unsupported']}
    assert reasons['catalog_limits.catalog_limits_unique'] == 'NULLS NOT DISTINCT is unsupported'
    assert reasons['catalog_limits.standalone_nulls_idx'] == 'NULLS NOT DISTINCT is unsupported'
    assert reasons['invalid_check.invalid_check_value_check'] == 'unsupported check expression'
    assert (
        reasons['catalog_limits.descending_idx']
        == 'non-default index order or collation is unsupported'
    )
    assert reasons['catalog_limits.opclass_idx'] == 'custom operator classes are unsupported'
    assert (
        reasons['catalog_limits.identity_value']
        == 'non-default identity sequence settings are unsupported'
    )
    assert reasons['cross_schema_reference.cross_schema_reference_parent_id_fkey'] == (
        'cross-schema foreign keys are unsupported'
    )
    assert reasons['catalog_limits.catalog_trigger'] == 'user triggers are unsupported'
    assert reasons['catalog_trigger()'] == 'user functions are unsupported'


@pytest.mark.integration
async def test_executor_rolls_back_transactional_plan_and_records_failure(database: str) -> None:
    baseline = {'tables': []}
    async with await psycopg.AsyncConnection.connect(database, row_factory=dict_row) as conn:
        await executor.initialize_tracking(conn, 'environment-1', 'revision-0', baseline)
    result = await executor.execute_plan(
        database,
        'public',
        'environment-1',
        'execution-1',
        'revision-0',
        'revision-1',
        baseline,
        {
            'steps': [
                {
                    'id': 'create-table',
                    'sql': 'CREATE TABLE should_rollback (id integer)',
                    'description': 'create temporary test table',
                    'transactional': True,
                    'impact': 'metadata',
                    'operation': {'kind': 'create_table'},
                },
                {
                    'id': 'break-plan',
                    'sql': 'ALTER TABLE missing_table ADD COLUMN value integer',
                    'description': 'force rollback',
                    'transactional': True,
                    'impact': 'metadata',
                    'operation': {'kind': 'add_column'},
                },
            ]
        },
    )
    assert result['status'] == 'failed'
    async with await psycopg.AsyncConnection.connect(database, row_factory=dict_row) as conn:
        missing = await conn.execute("SELECT to_regclass('public.should_rollback') AS relation")
        assert (await missing.fetchone())['relation'] is None
        state = await conn.execute('SELECT active_execution FROM "_proteus".state')
        assert (await state.fetchone())['active_execution'] is None
        migration = await conn.execute(
            'SELECT state FROM "_proteus".migrations WHERE execution_id = %s', ('execution-1',)
        )
        assert (await migration.fetchone())['state'] == 'failed'


@pytest.mark.integration
async def test_executor_bootstraps_an_untracked_zero_step_baseline(database: str) -> None:
    result = await executor.execute_plan(
        database,
        'public',
        'environment-bootstrap',
        'execution-bootstrap',
        None,
        'revision-baseline',
        {'tables': []},
        {'steps': []},
    )
    assert result == {'status': 'succeeded'}
    async with await psycopg.AsyncConnection.connect(database, row_factory=dict_row) as conn:
        state = await conn.execute('SELECT last_completed_revision FROM "_proteus".state')
        assert (await state.fetchone())['last_completed_revision'] == 'revision-baseline'


@pytest.mark.integration
async def test_executor_does_not_receipt_an_unverified_baseline(database: str) -> None:
    table_id, column_id = object_id(), object_id()
    expected = {
        'tables': [
            {
                'id': table_id,
                'name': 'missing_table',
                'columns': [
                    {
                        'id': column_id,
                        'name': 'id',
                        'data_type': 'integer',
                        'nullable': False,
                        'default': None,
                        'identity': None,
                    }
                ],
                'constraints': [],
                'indexes': [],
            }
        ]
    }
    result = await executor.execute_plan(
        database,
        'public',
        'environment-unverified',
        'execution-unverified',
        'revision-baseline',
        'revision-baseline',
        expected,
        {'steps': []},
    )
    assert result['status'] == 'failed'
    async with await psycopg.AsyncConnection.connect(database, row_factory=dict_row) as conn:
        state = await conn.execute(
            'SELECT last_completed_revision, active_execution FROM "_proteus".state'
        )
        assert (await state.fetchone()) == {
            'last_completed_revision': None,
            'active_execution': None,
        }


@pytest.mark.integration
async def test_executor_recovers_a_concurrent_index_crash_gap(database: str) -> None:
    table_id, column_id, index_id = object_id(), object_id(), object_id()
    baseline = {
        'tables': [
            {
                'id': table_id,
                'name': 'events',
                'columns': [
                    {
                        'id': column_id,
                        'name': 'occurred_at',
                        'data_type': 'timestamp',
                        'nullable': False,
                        'default': 'CURRENT_TIMESTAMP',
                        'identity': None,
                    }
                ],
                'constraints': [],
                'indexes': [],
            }
        ]
    }
    target = {
        'tables': [
            {
                **baseline['tables'][0],
                'indexes': [
                    {
                        'id': index_id,
                        'name': 'events_occurred_at_idx',
                        'columns': [column_id],
                        'unique': False,
                    }
                ],
            }
        ]
    }
    async with await psycopg.AsyncConnection.connect(database, row_factory=dict_row) as conn:
        await conn.execute(
            'CREATE TABLE events (occurred_at timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP)'
        )
        await conn.commit()
        await executor.initialize_tracking(conn, 'environment-2', 'revision-0', baseline)
    plan = {
        'steps': [
            {
                'id': 'create-index',
                'sql': 'CREATE INDEX CONCURRENTLY events_occurred_at_idx ON events (occurred_at)',
                'description': 'create online index',
                'transactional': False,
                'impact': 'index',
                'operation': {
                    'kind': 'create_index',
                    'schema': 'public',
                    'name': 'events_occurred_at_idx',
                    'table': 'events',
                    'unique': False,
                    'columns': ['occurred_at'],
                },
            }
        ]
    }
    async with await psycopg.AsyncConnection.connect(database, row_factory=dict_row) as conn:
        await executor._prepare_execution(
            conn,
            'environment-2',
            'execution-2',
            'revision-0',
            'revision-1',
            target,
            plan,
        )
    async with await psycopg.AsyncConnection.connect(database, autocommit=True) as conn:
        await conn.execute(
            'CREATE INDEX CONCURRENTLY events_occurred_at_idx ON events (occurred_at)'
        )
    assert await executor.execute_plan(
        database,
        'public',
        'environment-2',
        'execution-2',
        'revision-0',
        'revision-1',
        target,
        plan,
    ) == {'status': 'succeeded'}


@pytest.mark.integration
async def test_executor_marks_committed_not_valid_phase_needs_attention(database: str) -> None:
    table_id, column_id, constraint_id, index_id = (
        object_id(),
        object_id(),
        object_id(),
        object_id(),
    )
    baseline = {
        'tables': [
            {
                'id': table_id,
                'name': 'values_for_validation',
                'columns': [
                    {
                        'id': column_id,
                        'name': 'value',
                        'data_type': 'integer',
                        'nullable': True,
                        'default': None,
                        'identity': None,
                    }
                ],
                'constraints': [],
                'indexes': [],
            }
        ]
    }
    target = {
        'tables': [
            {
                **baseline['tables'][0],
                'constraints': [
                    {
                        'id': constraint_id,
                        'name': 'values_positive',
                        'kind': 'check',
                        'columns': [column_id],
                        'expression': 'value > 0',
                    }
                ],
                'indexes': [
                    {
                        'id': index_id,
                        'name': 'values_for_validation_idx',
                        'columns': [column_id],
                        'unique': False,
                    }
                ],
            }
        ]
    }
    async with await psycopg.AsyncConnection.connect(database, row_factory=dict_row) as conn:
        await conn.execute('CREATE TABLE values_for_validation (value integer)')
        await conn.execute('INSERT INTO values_for_validation VALUES (-1)')
        await conn.commit()
        await executor.initialize_tracking(conn, 'environment-validation', 'revision-0', baseline)
    plan = {
        'steps': [
            {
                'id': 'add-not-valid',
                'sql': 'ALTER TABLE values_for_validation ADD CONSTRAINT values_positive CHECK (value > 0) NOT VALID',
                'description': 'add check',
                'transactional': True,
                'impact': 'metadata',
                'operation': {'kind': 'add_constraint'},
            },
            {
                'id': 'validate',
                'sql': 'ALTER TABLE values_for_validation VALIDATE CONSTRAINT values_positive',
                'description': 'validate check',
                'transactional': True,
                'impact': 'scan',
                'operation': {'kind': 'validate_constraint'},
            },
            {
                'id': 'later-index',
                'sql': 'CREATE INDEX CONCURRENTLY values_for_validation_idx ON values_for_validation (value)',
                'description': 'make the plan multi-phase',
                'transactional': False,
                'impact': 'index',
                'operation': {
                    'kind': 'create_index',
                    'schema': 'public',
                    'name': 'values_for_validation_idx',
                    'table': 'values_for_validation',
                    'unique': False,
                    'columns': ['value'],
                },
            },
        ]
    }
    result = await executor.execute_plan(
        database,
        'public',
        'environment-validation',
        'execution-validation',
        'revision-0',
        'revision-1',
        target,
        plan,
    )
    assert result['status'] == 'needs_attention'
    async with await psycopg.AsyncConnection.connect(database, row_factory=dict_row) as conn:
        constraint = await conn.execute(
            "SELECT convalidated FROM pg_constraint WHERE conname = 'values_positive'"
        )
        assert (await constraint.fetchone())['convalidated'] is False
        state = await conn.execute('SELECT active_execution FROM "_proteus".state')
        assert (await state.fetchone())['active_execution'] == 'execution-validation'
        migration = await conn.execute(
            'SELECT state FROM "_proteus".migrations WHERE execution_id = %s',
            ('execution-validation',),
        )
        assert (await migration.fetchone())['state'] == 'needs_attention'
    async with await psycopg.AsyncConnection.connect(database) as conn:
        await conn.execute('UPDATE values_for_validation SET value = 1')
        await conn.commit()
    retry = await executor.execute_plan(
        database,
        'public',
        'environment-validation',
        'execution-validation',
        'revision-0',
        'revision-1',
        target,
        plan,
    )
    async with await psycopg.AsyncConnection.connect(database, row_factory=dict_row) as conn:
        captured = await catalog.introspect(conn, 'public', reference=target)
    assert captured['unsupported'] == []
    assert captured['snapshot'] == schema.validate_snapshot(target)
    assert retry == {'status': 'succeeded'}
