CREATE TABLE customers (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name text,
    email varchar(255) NOT NULL UNIQUE,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoices (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    customer_id bigint NOT NULL REFERENCES customers (id),
    invoice_number varchar(64) NOT NULL UNIQUE,
    amount_cents bigint NOT NULL CHECK (amount_cents >= 0),
    issued_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE invoice_items (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL REFERENCES invoices (id),
    description text NOT NULL,
    quantity integer NOT NULL CHECK (quantity >= 0),
    unit_amount_cents bigint NOT NULL CHECK (unit_amount_cents >= 0)
);

CREATE TABLE payments (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    invoice_id bigint NOT NULL REFERENCES invoices (id),
    amount_cents bigint NOT NULL CHECK (amount_cents >= 0),
    method varchar(32) NOT NULL DEFAULT 'card',
    paid_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO customers (name, email) VALUES
    ('Avery Chen', 'avery.chen@example.test'),
    ('Northstar Operations', 'billing@example.test'),
    ('Mina Patel', 'mina.patel@example.test');

INSERT INTO invoices (customer_id, invoice_number, amount_cents) VALUES
    (1, 'INV-1001', 12500),
    (1, 'INV-1002', 4800),
    (3, 'INV-1003', 21000);

INSERT INTO invoice_items (invoice_id, description, quantity, unit_amount_cents) VALUES
    (1, 'Database assessment', 1, 12500),
    (2, 'Schema review', 2, 2400),
    (3, 'Migration planning', 3, 7000);

INSERT INTO payments (invoice_id, amount_cents, method) VALUES
    (1, 12500, 'bank_transfer'),
    (2, 4800, DEFAULT),
    (3, 10000, 'card');
